[Variables]
; SimpleSkinHWiNFO configuration file
; by gabry3795 - gabry dot gabry at hotmail dot it

; Please replace every variable value with yours by using "HWiNFOSharedMemoryViewer.exe"
; in C:\Username\Documents\Rainmeter\Skin\SimpleSkinHWiNFO\@Resources

; => Motherboard Sensors
HWiNFO-MOBO-SensorId=0xf0008728
HWiNFO-MOBO-SensorInstance=0x0
HWiNFO-MOBO-CPU-Fan-Entry=0x3000000
HWiNFO-MOBO-CPU-Temp-Entry=0x1000000
HWiNFO-MOBO-Vcore-Entry=0x2000000
; ==> Voltages, in order :: +12V, +5V, +3.3V
HWiNFO-MOBO-twelveV-Entry=0x2000002
HWiNFO-MOBO-fiveV-Entry=0x2000003
HWiNFO-MOBO-threeV-Entry=0x2000004

; => CPU Sensors
HWiNFO-CPU0-SensorId=0xf0000300
HWiNFO-CPU0-SensorInstance=0x0
HWiNFO-CPU0-Bus-Entry=0x6000008
HWiNFO-CPU0-Core1-Usage-Entry=0x7000000
HWiNFO-CPU0-Core2-Usage-Entry=0x7000001
HWiNFO-CPU0-Core3-Usage-Entry=0x7000002
HWiNFO-CPU0-Core4-Usage-Entry=0x7000003
HWiNFO-CPU0-Core5-Usage-Entry=0x7000004
HWiNFO-CPU0-Core6-Usage-Entry=0x7000005
HWiNFO-CPU0-Core7-Usage-Entry=0x7000006
HWiNFO-CPU0-Core8-Usage-Entry=0x7000007
HWiNFO-CPU0-Core1-Clock-Entry=0x6000000
HWiNFO-CPU0-Core2-Clock-Entry=0x6000001
HWiNFO-CPU0-Core3-Clock-Entry=0x6000002
HWiNFO-CPU0-Core4-Clock-Entry=0x6000003
HWiNFO-CPU0-Core5-Clock-Entry=0x6000004
HWiNFO-CPU0-Core6-Clock-Entry=0x6000005
HWiNFO-CPU0-Core7-Clock-Entry=0x6000006
HWiNFO-CPU0-Core8-Clock-Entry=0x6000007
; => CPU Power Sensor (within my mobo CPU power has another SensorInstance)
HWiNFO-CPU0-Power-SensorId=0xf0000501
HWiNFO-CPU0-Power-SensorInstance=0x0
HWiNFO-CPU0-Power-Entry=0x5000000