; ------------------------------ styles ------------------------------
[Variables]
HWiNFOColor1=0, 255, 0, 255
HWiNFOColor2=255, 0, 0, 255
HWiNFOColor3=0, 204, 255, 255
HWiNFOColor4=255, 255, 255, 255
HWiNFOColor5=255, 255, 0, 255
MaxTickPointerColor=247,116,116,255
AvgTickPointerColor=247,238,153,255
MinTickPointerColor=153,247,153,255
CurrPointerColor=173,230,247,255
BackgroundRotator=50,50,50,255
BackgroudFillRotator=115,115,115,255
Column1=80
Column2=130
Column3=180
;Colors
White=255,255,255,255

[HWiNFOTextStyle]
FontColor=255, 255, 255, 255
FontFace=Tahoma
FontSize=8
AntiAlias=1

[HWiNFOGraphStyle]
LineColor=#HWiNFOColor1#
LineColor2=#HWiNFOColor2#
LineColor3=#HWiNFOColor3#
LineColor4=#HWiNFOColor4#
PrimaryColor=255, 255, 255, 237
SolidColor=96, 96, 96, 96
W=305
H=45
AntiAlias=1

[HWiNFOCoresGraphStyle]
LineColor=#BackgroundFillRotator#
LineColor2=#BackgroundFillRotator#
LineColor3=#BackgroundFillRotator#
LineColor4=#BackgroundFillRotator#
LineColor5=#BackgroundFillRotator#
LineColor6=#BackgroundFillRotator#
LineColor7=#BackgroundFillRotator#
LineColor8=#BackgroundFillRotator#
PrimaryColor=255, 255, 255, 237
SolidColor=96, 96, 96, 96
W=120
H=35
AntiAlias=1

[HWiNFOHeaderStyle]
FontFace=Verdana
FontColor=255, 255, 255, 255
FontSize=8
StringStyle=BOLD

[HWiNFOCoreInnerLabel]
FontFace=Verdana
FontColor=255,255,255,100
FontSize=7
StringStyle=THIN

[SectionHeaderLabelStyle]
Meter=String
FontFace=Verdana
FontColor=240, 240, 240, 255
FontSize=8
StringStyle=BOLD

[InnerPointerLabel]
FontFace=Verdana
FontColor=255,255,255,100
FontSize=7
StringStyle=THIN